### ISSUE TITLE
Create methods for cleaning, scaling and featuring data (on Jupyter notebooks)

### ISSUE THREAD

**Issue by joaquincrippa** [CryptoBotTeam889/cryptobot#3]
- [ ] Create a new feature based in the differenee between open and close value : "up / down"

- [ ] Merge actual CSV from BINANCE with Fear and Greed CSV from API

- [ ] Create functions to preprocess merged data

**Comment by Bajiks** [comment]
- Create a new feature based in the differenee between open and close value : "up / down"
- Merge actual CSV from BINANCE with Fear and Greed CSV from API
- Create functions to preprocess merged data
